// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC5AKUY4rdoOMoqmEaGdtCZPF6Yo_lEH_w',
    appId: '1:182267355568:web:27f1587be11a6fdcd9b675',
    messagingSenderId: '182267355568',
    projectId: 'sobitiye-cb37f',
    authDomain: 'sobitiye-cb37f.firebaseapp.com',
    databaseURL: 'https://sobitiye-cb37f-default-rtdb.firebaseio.com',
    storageBucket: 'sobitiye-cb37f.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBzioBDN8qEhX6e8eOwiD00sdDfFWPZLgY',
    appId: '1:182267355568:android:732fbcb384e57883d9b675',
    messagingSenderId: '182267355568',
    projectId: 'sobitiye-cb37f',
    databaseURL: 'https://sobitiye-cb37f-default-rtdb.firebaseio.com',
    storageBucket: 'sobitiye-cb37f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC_0dQIg-OPA2m093yvSKdbkC2Bm1utNu0',
    appId: '1:182267355568:ios:cd7d62d37e5428c4d9b675',
    messagingSenderId: '182267355568',
    projectId: 'sobitiye-cb37f',
    databaseURL: 'https://sobitiye-cb37f-default-rtdb.firebaseio.com',
    storageBucket: 'sobitiye-cb37f.appspot.com',
    iosClientId: '182267355568-ld543ufm35mtr1ab8lduod182vq6h8d7.apps.googleusercontent.com',
    iosBundleId: 'sobitie.2023.3',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC_0dQIg-OPA2m093yvSKdbkC2Bm1utNu0',
    appId: '1:182267355568:ios:daa4e3f130c6b1d0d9b675',
    messagingSenderId: '182267355568',
    projectId: 'sobitiye-cb37f',
    databaseURL: 'https://sobitiye-cb37f-default-rtdb.firebaseio.com',
    storageBucket: 'sobitiye-cb37f.appspot.com',
    iosClientId: '182267355568-vd2b37hqviaea4vf7m4ji28e1johdngc.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApplication1',
  );
}
